---

- name: Run Terraform Module - Remote VPNaaS Orchestration
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:
  - name: Terraform Plan - AWS SSH Key
    terraform:
      project_path: '$HOME/coding/github.com/ciscops/TerraformBluePrints/prod/scalable_ravpn_r53/0_aws_ssh_key'
      state: planned
      plan_file: 'terraform.tfplan'
      variables_file: '$HOME/coding/github.com/ciscops/TerraformBluePrints/prod/scalable_ravpn_r53/variables/main.tfvars'
      force_init: yes
    tags: plan-0-ssh-key

  - name: Terraform - Apply
    terraform:
      project_path: '$HOME/coding/github.com/ciscops/TerraformBluePrints/prod/scalable_ravpn_r53/0_aws_ssh_key'
      state: present
      plan_file: 'terraform.tfplan'
      variables_file: '$HOME/coding/github.com/ciscops/TerraformBluePrints/prod/scalable_ravpn_r53/variables/main.tfvars'
    tags: apply-0-ssh-key

  - name: Terraform Plan - AWS Network Provision (VPC)
    terraform:
      project_path: '$HOME/coding/github.com/ciscops/TerraformBluePrints/prod/scalable_ravpn_r53/1_aws_network'
      state: planned
      plan_file: 'terraform.tfplan'
      variables_file: '$HOME/coding/github.com/ciscops/TerraformBluePrints/prod/scalable_ravpn_r53/variables/main.tfvars'
      force_init: yes
    tags: plan-1-aws-network

  - name: Terraform - Apply - AWS Network Provision (VPC)
    terraform:
      project_path: '$HOME/coding/github.com/ciscops/TerraformBluePrints/prod/scalable_ravpn_r53/1_aws_network'
      state: present
      plan_file: 'terraform.tfplan'
      variables_file: '$HOME/coding/github.com/ciscops/TerraformBluePrints/prod/scalable_ravpn_r53/variables/main.tfvars'
    tags: apply-1-aws-network

  - name: Terraform Plan - TGW Associations
    terraform:
      project_path: '$HOME/coding/github.com/ciscops/TerraformBluePrints/prod/scalable_ravpn_r53/2_tgw_associations'
      state: planned
      plan_file: 'terraform.tfplan'
      variables_file: '$HOME/coding/github.com/ciscops/TerraformBluePrints/prod/scalable_ravpn_r53/variables/main.tfvars'
      force_init: yes
    tags: plan-2_tgw_associations

  - name: Terraform - Apply - TGW Associations
    terraform:
      project_path: '$HOME/coding/github.com/ciscops/TerraformBluePrints/prod/scalable_ravpn_r53/2_tgw_associations'
      state: present
      plan_file: 'terraform.tfplan'
      variables_file: '$HOME/coding/github.com/ciscops/TerraformBluePrints/prod/scalable_ravpn_r53/variables/main.tfvars'
    tags: apply-2_tgw_associations

  - name: Terraform Plan - ASAv Configuration
    terraform:
      project_path: '$HOME/coding/github.com/ciscops/TerraformBluePrints/prod/scalable_ravpn_r53/3_asav_config'
      state: planned
      plan_file: 'terraform.tfplan'
      variables_file: '$HOME/coding/github.com/ciscops/TerraformBluePrints/prod/scalable_ravpn_r53/variables/main.tfvars'
      force_init: yes
    tags: plan-3_asav_config

  - name: Terraform - Apply - ASAv Configuration
    terraform:
      project_path: '$HOME/coding/github.com/ciscops/TerraformBluePrints/prod/scalable_ravpn_r53/3_asav_config'
      state: present
      plan_file: 'terraform.tfplan'
      variables_file: '$HOME/coding/github.com/ciscops/TerraformBluePrints/prod/scalable_ravpn_r53/variables/main.tfvars'
    tags: apply-3_asav_config

  - name: Terraform Plan - Route 53 Front End
    terraform:
      project_path: '$HOME/coding/github.com/ciscops/TerraformBluePrints/prod/scalable_ravpn_r53/4_aws_r53_frontend'
      state: planned
      plan_file: 'terraform.tfplan'
      variables_file: '$HOME/coding/github.com/ciscops/TerraformBluePrints/prod/scalable_ravpn_r53/variables/main.tfvars'
      force_init: yes
    tags: plan-4_aws_r53_frontend

  - name: Terraform - Apply - Route 53 Front End
    terraform:
      project_path: '$HOME/coding/github.com/ciscops/TerraformBluePrints/prod/scalable_ravpn_r53/4_aws_r53_frontend'
      state: present
      plan_file: 'terraform.tfplan'
      variables_file: '$HOME/coding/github.com/ciscops/TerraformBluePrints/prod/scalable_ravpn_r53/variables/main.tfvars'
    tags: apply-4_aws_r53_frontend

  - name: Terraform Plan - Deploy ASAv Configurations
    terraform:
      project_path: '$HOME/coding/github.com/ciscops/TerraformBluePrints/prod/scalable_ravpn_r53/5_asav_deployment'
      state: planned
      plan_file: 'terraform.tfplan'
      variables_file: '$HOME/coding/github.com/ciscops/TerraformBluePrints/prod/scalable_ravpn_r53/variables/main.tfvars'
      force_init: yes
    tags: plan-5_asav_deployment

  - name: Terraform - Apply - Deploy ASAv Configurations
    terraform:
      project_path: '$HOME/coding/github.com/ciscops/TerraformBluePrints/prod/scalable_ravpn_r53/5_asav_deployment'
      state: present
      plan_file: 'terraform.tfplan'
      variables_file: '$HOME/coding/github.com/ciscops/TerraformBluePrints/prod/scalable_ravpn_r53/variables/main.tfvars'
    tags: apply-5_asav_deployment

  #- meta: refresh_inventory
  #  tags: always
        
