---

- name: Run Terraform Module
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:
  - name: Terraform Plan
    terraform:
      project_path: '$HOME/coding/github.com/ciscops/TerraformBluePrints/prod/scalable_ravpn_r53/0_aws_ssh_key'
      state: planned
      plan_file: 'terraform.tfplan'
      variables_file: '$HOME/coding/github.com/ciscops/TerraformBluePrints/prod/scalable_ravpn_r53/variables/main.tfvars'
      force_init: yes
    tags: plan-ssh-key

  - name: Terraform - Apply
    terraform:
      project_path: '$HOME/coding/github.com/ciscops/TerraformBluePrints/prod/scalable_ravpn_r53/0_aws_ssh_key'
      state: present
      plan_file: 'terraform.tfplan'
      variables_file: '$HOME/coding/github.com/ciscops/TerraformBluePrints/prod/scalable_ravpn_r53/variables/main.tfvars'
    tags: apply-ssh-key

  #- meta: refresh_inventory
  #  tags: always
        
